spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Bank_DB
    username: gnemirko
    password: 1214
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: false   # если миграции не нужны локально

# очень важно: чтобы spring не пытался поднимать docker-compose при локальном запуске
spring.docker.compose.enabled: false

server:
  port: 8081
logging.level.com.gnemirko.bank_rest: DEBUG